version: 2
jobs:
  vs-ponyc:
    docker:
      - image: superherointj/ponylang-archlinux-sdl
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc
